/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import gestorEmpleado.GestorEmpleado;

/**
 *
 * @author Javiera Jara, Alvaro Vega, Felipe Vogt
 */
public class GuiAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form GuiAdministrador
     */
    GestorEmpleado gestorEmpleado;
    public GuiAdministrador(GestorEmpleado gestorEmpleado) {
        initComponents();
        this.gestorEmpleado = gestorEmpleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGestEmp = new javax.swing.JButton();
        botonLiquid = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonGestEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonGestEmp.setText("Gestionar Empleado");
        botonGestEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestEmpActionPerformed(evt);
            }
        });

        botonLiquid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonLiquid.setText("Liquidaciones");
        botonLiquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLiquidActionPerformed(evt);
            }
        });

        botonRegresar.setText("Back");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLiquid, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestEmp))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonRegresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(botonGestEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonLiquid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLiquidActionPerformed
        
        GuiLiquidacion guiLiquidacion= new GuiLiquidacion(this.gestorEmpleado);
        guiLiquidacion.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonLiquidActionPerformed

    private void botonGestEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestEmpActionPerformed
       GuiGestionarEmpleado guiGestionarEmpleado= new GuiGestionarEmpleado(this.gestorEmpleado);
       guiGestionarEmpleado.setVisible(true);
       this.setVisible(false);
      
    }//GEN-LAST:event_botonGestEmpActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        GuiPrincipal guiPrincipal = new GuiPrincipal();
        guiPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGestEmp;
    private javax.swing.JButton botonLiquid;
    private javax.swing.JButton botonRegresar;
    // End of variables declaration//GEN-END:variables
}
