/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import gestorArchivo.ArchivoLiquidacion;
import gestorEmpleado.GestorEmpleado;
import gestorEmpleado.Liquidacion;
import gestorEmpleado.Validacion;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Javiera Jara, Alvaro Vega, Felipe Vogt
 */
public class GuiLiquidacion extends javax.swing.JFrame {

    /**
     * Creates new form GuiLiquidacion
     */
   
    DefaultListModel modeloLista = new DefaultListModel();
    GestorEmpleado gestorEmpleado;
    Liquidacion liquidacion = new Liquidacion();
    
    public GuiLiquidacion(GestorEmpleado gestorEmpleado) {
        initComponents();
        this.gestorEmpleado = gestorEmpleado;
        this.listaEmpleados.setModel(modeloLista);
        for (int i = 0; i < gestorEmpleado.getEmpleados().size(); i++){
            modeloLista.addElement(gestorEmpleado.getEmpleados().get(i));
        }
        this.botonGeneLiqui.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        comboMes = new javax.swing.JComboBox<>();
        comboAno = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        botonGeneLiqui = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane2.setViewportView(jEditorPane1);

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaEmpleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaEmpleados);

        jLabel1.setText("Fecha:");

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione mes:", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        comboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesActionPerformed(evt);
            }
        });

        comboAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione año;", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));

        jLabel2.setText("Mes");

        jLabel3.setText("Año");

        jLabel4.setText("Nombre");

        jLabel6.setText("Rut");

        botonRegresar.setText("Back");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        botonGeneLiqui.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonGeneLiqui.setText("Generar Liquidacion");
        botonGeneLiqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneLiquiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comboMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comboAno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonRegresar)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonGeneLiqui, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(comboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botonGeneLiqui, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(botonRegresar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGeneLiquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneLiquiActionPerformed
        Validacion val = new Validacion();
        if(val.validarArchivoRegistro(gestorEmpleado.getEmpleados().get(listaEmpleados.getSelectedIndex()).getRut(), (String)this.comboMes.getSelectedItem(), (String)this.comboAno.getSelectedItem()) == true){
            
           int diasTrabajados = gestorEmpleado.calcularDiasTrabajados(this.listaEmpleados.getSelectedIndex(), (String)this.comboMes.getSelectedItem(), (String)this.comboAno.getSelectedItem());
           int horasMensuales = gestorEmpleado.calcularHorasMensuales(this.listaEmpleados.getSelectedIndex(), (String)this.comboMes.getSelectedItem(), (String)this.comboAno.getSelectedItem());
           int horasExtrasMensuales = gestorEmpleado.calcularHorasExtrasMensuales(this.listaEmpleados.getSelectedIndex(), (String)this.comboMes.getSelectedItem(), (String)this.comboAno.getSelectedItem());
           int valorHora = gestorEmpleado.getValorHora(gestorEmpleado.getEmpleados().get(this.listaEmpleados.getSelectedIndex()).getCodTrabajo());
           int valorHoraExtra = gestorEmpleado.getValorHoraExtra(gestorEmpleado.getEmpleados().get(this.listaEmpleados.getSelectedIndex()).getCodTrabajo());
           double descAfiliacion = gestorEmpleado.getDescuentoAfiliacion(gestorEmpleado.getEmpleados().get(this.listaEmpleados.getSelectedIndex()).getCodAfiliacion());
           double descSalud = gestorEmpleado.getDescuentoSalud(gestorEmpleado.getEmpleados().get(this.listaEmpleados.getSelectedIndex()).getCodSalud());
           double descSeguro = gestorEmpleado.getDescuentoSeguro(gestorEmpleado.getEmpleados().get(this.listaEmpleados.getSelectedIndex()).getCodSeguro());
           
            int sueldoBase = liquidacion.calcularSueldoBase(horasMensuales, valorHora);
            int adicionalHorasExtras = liquidacion.calcularAdicionalHorasExtras(horasExtrasMensuales, valorHoraExtra);
            int sueldoBruto = liquidacion.calcularSueldoBruto(sueldoBase, adicionalHorasExtras);
            
            double descuentoAfp = liquidacion.calcularDescuento(sueldoBruto, descAfiliacion);
            double descuentoSalud = liquidacion.calcularDescuento(sueldoBruto, descSalud);
            double descuentoSeguro = liquidacion.calcularDescuento(sueldoBruto, descSeguro);
            double totalDescuento = descuentoAfp + descuentoSalud + descuentoSeguro;
            
            double sueldoLiquido = liquidacion.calcularSueldoLiquido(descuentoAfp, descuentoSalud, descuentoSeguro, sueldoBruto);
            
            gestorEmpleado.guardarLiquidacion(this.listaEmpleados.getSelectedIndex(), this.comboMes.getSelectedItem().toString(), this.comboAno.getSelectedItem().toString(), String.valueOf(diasTrabajados), String.valueOf(horasMensuales), String.valueOf(horasExtrasMensuales),
                    String.valueOf(sueldoBase),String.valueOf(adicionalHorasExtras), String.valueOf(sueldoBruto),
                    String.valueOf(descuentoAfp), String.valueOf(descuentoSalud), String.valueOf(descuentoSeguro), String.valueOf(totalDescuento),
                    String.valueOf(sueldoLiquido));
        }else{
            JOptionPane.showMessageDialog(null, "No existe registro de la fecha indicada");
        }

    }//GEN-LAST:event_botonGeneLiquiActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        GuiAdministrador guiAdministrador = new GuiAdministrador(this.gestorEmpleado);
        guiAdministrador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void listaEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaEmpleadosValueChanged
        this.botonGeneLiqui.setEnabled(true);
    }//GEN-LAST:event_listaEmpleadosValueChanged

    private void comboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMesActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGeneLiqui;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comboAno;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaEmpleados;
    // End of variables declaration//GEN-END:variables
}
