/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;


import gestorEmpleado.GestorEmpleado;
import gestorEmpleado.Validacion;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Javiera Jara, Alvaro Vega, Felipe Vogt
 */
public class GuiRegistrarEmpleado extends javax.swing.JFrame {
    
    Validacion val = new Validacion();
    GestorEmpleado ge;
    /**
     * Creates new form GuiGestionarEmpleado
     */
    public GuiRegistrarEmpleado(GestorEmpleado gestorEmpleado) {
        initComponents();
        ge = gestorEmpleado;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldRut = new javax.swing.JTextField();
        comboBoxSexo = new javax.swing.JComboBox<>();
        comboBoxEstadoCivil = new javax.swing.JComboBox<>();
        comboBoxTrabajo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboBoxAfp = new javax.swing.JComboBox<>();
        comboBoxSalud = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldHorasPorDia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        textFieldApellidoPaterno = new javax.swing.JTextField();
        textFieldApellidoMaterno = new javax.swing.JTextField();
        botonGuardad = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        comboBoxSeguro = new javax.swing.JComboBox<>();
        jDateFecNacimiento = new com.toedter.calendar.JDateChooser();
        jDateFecIngreso = new com.toedter.calendar.JDateChooser();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Rut:");

        jLabel3.setText("Sexo:");

        jLabel4.setText("Fecha ingreso:");

        jLabel5.setText("Estado civil:");

        jLabel6.setText("Tipo de Trabajo:");

        jLabel7.setText("Afiliación:");

        jLabel8.setText("Salud:");

        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });

        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sexo:", "Mujer", "Hombre" }));
        comboBoxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSexoActionPerformed(evt);
            }
        });

        comboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estado:", "Soltero/a", "Casado/a", "Viudo/a", "Divorciado/a", "Separado/a" }));

        comboBoxTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Trabajo", "Carpintero", "Jornal", "Arquitecto", "Pintor", "AutoControl" }));
        comboBoxTrabajo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxTrabajoItemStateChanged(evt);
            }
        });
        comboBoxTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTrabajoActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha nacimiento:");

        comboBoxAfp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Afiliación", "Capital", "Cuprum", "Habitat", "Modelo", "Planvital", "Provida" }));
        comboBoxAfp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxAfpItemStateChanged(evt);
            }
        });

        comboBoxSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Isapre Banmedica", "Isapre Colmena Golden", "Isapre Cruzblanca", "Isapre Consalud", "Fonasa A", "Fonasa B", "Fonasa C", "Fonasa D" }));
        comboBoxSalud.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxSaludItemStateChanged(evt);
            }
        });
        comboBoxSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSaludActionPerformed(evt);
            }
        });

        jLabel16.setText("Telefono:");

        jLabel17.setText("Horas por dia:");

        jLabel18.setText("Apellido Paterno:");

        jLabel19.setText("Apellido Materno:");

        textFieldApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldApellidoMaternoActionPerformed(evt);
            }
        });

        botonGuardad.setText("Guardar");
        botonGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardadActionPerformed(evt);
            }
        });

        jLabel20.setText("Seguro:");

        comboBoxSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione seguro:", "Seguro Cesantia" }));

        botonRegresar.setText("Back");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateFecIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxEstadoCivil, 0, 165, Short.MAX_VALUE)
                    .addComponent(textFieldApellidoMaterno)
                    .addComponent(textFieldRut)
                    .addComponent(textFieldTelefono)
                    .addComponent(textFieldHorasPorDia)
                    .addComponent(textFieldApellidoPaterno)
                    .addComponent(textFieldNombre)
                    .addComponent(jDateFecNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxAfp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxTrabajo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxSalud, 0, 204, Short.MAX_VALUE)
                            .addComponent(comboBoxSeguro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonGuardad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(comboBoxAfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldHorasPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateFecNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateFecIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonGuardad)
                        .addComponent(botonRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSexoActionPerformed

    private void textFieldApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldApellidoMaternoActionPerformed

    private void botonGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardadActionPerformed
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        if (val.validarNombreApellido(textFieldNombre.getText()) == true ){
            String nomb = textFieldNombre.getText();
            if (val.validarNombreApellido(textFieldApellidoPaterno.getText()) == true){
                String apPaterno = textFieldApellidoPaterno.getText();
                if (val.validarNombreApellido(textFieldApellidoMaterno.getText()) == true){
                    String apMaterno = textFieldApellidoMaterno.getText();
                    if (val.validarRut(textFieldRut.getText()) == true && val.validarRutRepedito(textFieldRut.getText(), ge) != true){
                        String empRut = textFieldRut.getText();
                        if (val.validarTelefono(textFieldTelefono.getText()) == true){
                            String fono = textFieldTelefono.getText();
                            if (val.validarHoras(textFieldHorasPorDia.getText()) == true){
                                int hrsPorDia = Integer.parseInt(textFieldHorasPorDia.getText());
                                if (jDateFecNacimiento.getDate() == null){
                                    JOptionPane.showMessageDialog(null, "Fecha invalida");
                                }else{
                                    String fechaNacimiento = formato.format(jDateFecNacimiento.getDate());
                                    if (comboBoxSexo.getSelectedIndex() != 0){
                                        String sex = comboBoxSexo.getSelectedItem().toString();
                                        if (comboBoxEstadoCivil.getSelectedIndex() != 0){
                                            String estCivil = comboBoxEstadoCivil.getSelectedItem().toString();
                                            if (jDateFecIngreso.getDate() == null){
                                                JOptionPane.showMessageDialog(null, "Fecha invalida");
                                            }else{
                                                String fechaIngreso = formato.format(jDateFecIngreso.getDate());
                                                if (comboBoxTrabajo.getSelectedIndex() != 0){
                                                String codTrabjo = String.valueOf(comboBoxTrabajo.getSelectedIndex());
                                                    if (comboBoxAfp.getSelectedIndex() != 0){
                                                        String codAfiliacion = String.valueOf(comboBoxAfp.getSelectedIndex());
                                                        if (comboBoxSalud.getSelectedIndex() != 0){
                                                            String codSalud = String.valueOf(comboBoxSalud.getSelectedIndex());
                                                            if (comboBoxSeguro.getSelectedIndex() != 0){
                                                                String codSeguro = String.valueOf(comboBoxSeguro.getSelectedIndex());
                                                                ge.agregarEmpleado(empRut, nomb, apPaterno, apMaterno, fechaNacimiento, fechaIngreso, fono, sex, 
                                                                        estCivil, hrsPorDia, codTrabjo, codSalud, codSeguro, codAfiliacion);
                                                                ge.guardarEmpleado(empRut, nomb, apPaterno, apMaterno, fechaNacimiento, fechaIngreso, fono, sex,
                                                                        estCivil, hrsPorDia, codTrabjo, codSalud, codSeguro, codAfiliacion);
                                                                JOptionPane.showMessageDialog(null, "Datos guardados con exito!");
                                                                GuiGestionarEmpleado guiGE = new GuiGestionarEmpleado(this.ge);
                                                                guiGE.setVisible(true);
                                                                this.setVisible(false);
                                                            }else{
                                                                JOptionPane.showMessageDialog(null, "Seleccione Seguro");
                                                            }
                                                        }else{
                                                            JOptionPane.showMessageDialog(null, "Seleccione Isapre o Fonasa");
                                                        }
                                                    }else{
                                                        JOptionPane.showMessageDialog(null, "Seleccione afiliación");
                                                    }
                                                }else{
                                                    JOptionPane.showMessageDialog(null, "Seleccione trabajo");
                                                }
                                            }
                                        }else{
                                            JOptionPane.showMessageDialog(null, "Seleccione estado civil");
                                        }
                                    }else{
                                        JOptionPane.showMessageDialog(null, "Seleccione sexo");
                                    }
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "Horas invalidas o en blanco");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Telefono invalido o en blanco");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "RUT invalido o en blanco");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Apellido Materno invalido o en blanco");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Apellido Paterno invalido o en blanco");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nombre invalido o en blanco");
        }
    }//GEN-LAST:event_botonGuardadActionPerformed

    private void comboBoxAfpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxAfpItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxAfpItemStateChanged

    private void comboBoxSaludItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxSaludItemStateChanged
        
    }//GEN-LAST:event_comboBoxSaludItemStateChanged

    private void comboBoxSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSaludActionPerformed

    private void comboBoxTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTrabajoActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        GuiGestionarEmpleado guiGE = new GuiGestionarEmpleado(this.ge);
        guiGE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private void comboBoxTrabajoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxTrabajoItemStateChanged
        
    }//GEN-LAST:event_comboBoxTrabajoItemStateChanged
 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardad;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JComboBox<String> comboBoxAfp;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil;
    private javax.swing.JComboBox<String> comboBoxSalud;
    private javax.swing.JComboBox<String> comboBoxSeguro;
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JComboBox comboBoxTrabajo;
    private com.toedter.calendar.JDateChooser jDateFecIngreso;
    private com.toedter.calendar.JDateChooser jDateFecNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textFieldApellidoMaterno;
    private javax.swing.JTextField textFieldApellidoPaterno;
    private javax.swing.JTextField textFieldHorasPorDia;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldRut;
    private javax.swing.JTextField textFieldTelefono;
    // End of variables declaration//GEN-END:variables

   

  
}
